"""Template inventory - supported template identifiers.

These represent user-supplied HTML templates that may or may not exist
in the repository. The template loader will mark them as unavailable
if the HTML source file has not been supplied yet.
"""

TEMPLATE_INVENTORY = [
    {
        "template_id": "01_Focus_Habits_Shorts_9x16",
        "name": "Focus Habits Shorts",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "02_Geeta_Gyaan_9x16",
        "name": "Geeta Gyaan",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "03_General_Quiz_9x16",
        "name": "General Quiz",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "04_Science_Quiz_9x16",
        "name": "Science Quiz",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "05_Science_Storytelling_9x16",
        "name": "Science Storytelling",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "06_Indian_Traditional_Story_9x16",
        "name": "Indian Traditional Story",
        "format": "youtube_short",
        "aspect_ratio": "9:16",
        "adapter_id": "shorts_9x16",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "07_Indian_Heritage_Story_16x9",
        "name": "Indian Heritage Story",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "08_Crime_Files_16x9",
        "name": "Crime Files",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "09_Finance_Base_16x9",
        "name": "Finance Base",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "10_Finance_Wall_Street_Terminal_16x9",
        "name": "Finance Wall Street Terminal",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "11_Finance_Luxury_Wealth_16x9",
        "name": "Finance Luxury Wealth",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "12_Finance_Economic_Documentary_16x9",
        "name": "Finance Economic Documentary",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "13_Finance_Future_FinTech_16x9",
        "name": "Finance Future FinTech",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "14_AI_Neural_Intelligence_16x9",
        "name": "AI Neural Intelligence",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "15_AI_Digital_Future_16x9",
        "name": "AI Digital Future",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "16_Newsroom_16x9",
        "name": "Newsroom",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "17_Sports_Arena_16x9",
        "name": "Sports Arena",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "18_Entertainment_Red_Carpet_16x9",
        "name": "Entertainment Red Carpet",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
    {
        "template_id": "19_Movies_Recommendation_16x9",
        "name": "Movies Recommendation",
        "format": "youtube_long",
        "aspect_ratio": "16:9",
        "adapter_id": "long_16x9",
        "available": False,
        "source_path": None,
    },
]
